### PR TITLE
Fixing Broken Image

### PR DESCRIPTION
**Pull request by tweissaz**
Adding a placeholder image for broken image references and updated website/README.

### CODE REVIEW

**Review by lboeman — COMMENTED** [review]
Oh, I didn't realize you were using this for both lol. Kinda weird. Is there a more generic placeholder we can use for Lauren?

**Comment by tweissaz** [comment]
Abandoning this as per @lboeman's commend.

**Comment by tweissaz** [comment]
> Abandoning this as per @lboeman's commend.

thanks for commending me @lboeman, i of course meant comment... but alas.

**Comment by lboeman** [comment]
> > Abandoning this as per @lboeman's commend.
> 
> thanks for commending me @lboeman, i of course meant comment... but alas.

Your efforts to rectify this error are commendable.

**Pull request closed without merging**
